spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration, classpath:db/seed
  jpa:
    hibernate:
     ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID:ENC(3L5+cJ3QhPyprBUX8YOsqTuZnMOJyVBwi2gjlc2KVQzWz8J77heh1SvQyxcSGfrXAVQQbLpw2lcM1vBgkZEx4fFujLvL2dEvYnQf4dcq3I//yfArD8acow==)}
            client-secret: ${OAUTH_CLIENT_SECRET:ENC(VlfYz991G5XtohGbAWU/vsHZkW3/y7ILKIfyqy5Vy0d2HcbEDDgMySkfKDsgX8uw)}
            scope:
              - profile
              - email
            redirect-uri: ${OAUTH_REDIRECT_URI:https://dongkyurami.link/}
logging:
  level:
    com.kdt: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
cors:
  allowed:
    origin:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - https://127.0.0.1:3000
      - https://localhost:3000
jwt:
  client-secret: ${JWT_SECRET:DEFAULT_JWT_SECRET}
cookie:
  secure: ${COOKIE_SECURE:false}
  same-site: ${COOKIE_SAME_SITE:lax}
encryptor:
  key: ${ENCRYPTOR_KEY}