INSERT IGNORE INTO users(id, username, password, nickname) VALUES (1, 'eli221', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Elizabath');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (2, 'crong88', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Crong');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (3, 'hyeb22', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'hyeb');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (4, 'pjh612', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Null');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (5, 'midasq', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'mark');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (6, 'jkb221', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Lawrence');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (7, 'papa22', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'papa');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (8, 'jeongki', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Thompson');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (9, 'ssy221', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Claire');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (10, 'kyu221', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'regyu');
INSERT IGNORE INTO users(id, username, password, nickname) VALUES (11, 'dong22', '$2a$12$e/n5T8uw2kqCx15f7zCeruPcoRlAJJr1pLVubCoU45HeMPeOpeaZq', 'Dong-Young Kim');